### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [vickylance/Library-Books-Manager#1]
Good day @vickylance ,

Question can you maybe shed some light on this question will it slow this application down if there was over 100000 entries of books in .json file?

**Comment by vickylance** [comment]
@di48l069 Hi,
Since it is a JSON it should not have any major performance issues also I am using Newtonsoft JSON which is very efficient. you can check its parsing speed here http://www.newtonsoft.com/json where it says performance comparison. But there is another library called LitJSON which is also very light weight.

**Comment by vickylance** [comment]
@di48l069 
Also just a fair warning though the script is not completed, so if you are using it for any project just use it as a reference purpose.

**Comment by ghost** [comment]
@vickylance Thanks just going to use it as reference. Do you have any plans finishing it?

**Comment by vickylance** [comment]
@di48l069 I am not going to work on it in the near future but I think the rest of the things must be fairly easy.

**Comment by ghost** [comment]
@vickylance Agreed
